name: Install
on: [push]
jobs:
  manifest:
    name: Generate istio manifest
    runs-on: local-linux
    steps:        
      - name: Install Istio
        uses: deepakdeore2004/actions-istio-install@master
        with:
          istio version: '1.6.5'
          override file: 'values.yaml'

